#!/bin/sh

devtrac=hoge.hoge.co.jp
build_libjexport_dir=/root/build_libjexport
polling_dir=$build_libjexport_dir/polling
user=hoge
pass=hoge
last_rev=`cat $polling_dir/last_rev`
revision=`LC_ALL=en_US.UTF8 svn info --no-auth-cache --username $user --password $pass  svn://$devtrac/coreengine/tags | grep "Last Changed Rev"|sed -e "s/[^0-9]//g"`

if [ $last_rev -ge $revision  ];then  echo 'リビジョンの更新はありません。'; exit 0; fi

tag_list=`svn list --no-auth-cache --username $user --password $pass svn://$devtrac/coreengine/tags| grep 'tag[0-9]\{6\}_[0-9]\{2\}/'`

#渡された文字列配列の各要素について数値の並びだけを抽出し、もっとも大きい数字の要素を返す
get_newest_element() {
    local newest_str=0
    for arg in $@
    do
        [ `echo $newest_str| sed -e "s/[^0-9]//g"` '<' `echo $arg| sed -e "s/[^0-9]//g"` ] && newest_str="${arg}"
    done
    echo $newest_str
}

newest_tag=`get_newest_element $tag_list|sed -e "s/\///g"`
/bin/sh $build_libjexport_dir/run.sh $user $pass $newest_tag
echo $revision > $polling_dir/last_rev

